@API_HostAddress = http://localhost:5007

### Get all Race Cart Type IDs
GET {{API_HostAddress}}/model/racecarttype/id
Accept: application/json

> {%
    client.test("Request should be successful", function () {
        client.assert(response.status === 200, "Expected HTTP 200");
        client.assert(response.body.length > 0, "Expected to find at least one ID");

        // Extract the first ID dynamically and save it for the subsequent requests
        client.global.set("race_cart_type_id", response.body[0].id);
    });
%}


### Get all simple Race Cart Type entities
GET {{API_HostAddress}}/model/racecarttype/entity
Accept: application/json

> {%
    client.test("Request should return all simple entities", function () {
        client.assert(response.status === 200, "Expected HTTP 200");
        client.assert(Array.isArray(response.body), "Expected response to be an array");
    });
%}


### Get simple Race Cart Type entity by ID
GET {{API_HostAddress}}/model/racecarttype/entity/{{race_cart_type_id}}
Accept: application/json

> {%
    client.test("Request should return simple entity", function () {
        client.assert(response.status === 200, "Expected HTTP 200");
        client.assert(response.body.id === client.global.get("race_cart_type_id"), "ID mismatch");
    });
%}


### Get all complex Race Cart Type entities
GET {{API_HostAddress}}/model/racecarttype/complex
Accept: application/json

> {%
    client.test("Request should return all complex entities", function () {
        client.assert(response.status === 200, "Expected HTTP 200");
        client.assert(Array.isArray(response.body), "Expected response to be an array");
    });
%}


### Get complex Race Cart Type entity by ID
GET {{API_HostAddress}}/model/racecarttype/complex/{{race_cart_type_id}}
Accept: application/json

> {%
    client.test("Request should return complex entity", function () {
        client.assert(response.status === 200, "Expected HTTP 200");
        client.assert(response.body.id === client.global.get("race_cart_type_id"), "ID mismatch");
    });
%}


### Test 404 behavior for non-existing entity
GET {{API_HostAddress}}/model/racecarttype/complex/00000000-0000-0000-0000-000000000000
Accept: application/json

> {%
    client.test("Request should return 404 NotFound", function () {
        client.assert(response.status === 404, "Expected HTTP 404");
    });
%}